version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - python train.py
      - aws s3 cp model.pkl s3://mlops-app-bucket/model.pkl
